const fs = require('fs'); 
let html = fs.readFileSync('temp-render.html', 'utf8'); 
html = html.replace(/<title>.*?<\/title>/, "<title><%= siteSettings && siteSettings.siteName ? siteSettings.siteName : 'Ravenzena Bot' %> | Layanan Bot WhatsApp</title>"); 
html = html.replace(/content="Bot WhatsApp untuk komunitas yang lebih rapi dan aktif\."/g, 'content="<%= siteSettings && siteSettings.siteDescription ? siteSettings.siteDescription : \'Bot WhatsApp untuk komunitas yang lebih rapi dan aktif.\' %>"'); 
html = html.replace(/property="og:title" content="Ravenzena Bot"/, 'property="og:title" content="<%= siteSettings && siteSettings.siteName ? siteSettings.siteName : \'Ravenzena Bot\' %>"'); 
html = html.replace(/property="og:image" content="\/favicon\.png"/, 'property="og:image" content="<%= siteSettings && siteSettings.heroImageUrl ? siteSettings.heroImageUrl : \'/favicon.png\' %>"'); 
html = html.replace(/<img src="\/favicon\.png"/g, '<img src="<%= siteSettings && siteSettings.logoUrl ? siteSettings.logoUrl : \'/favicon.png\' %>"'); 
html = html.replace(/<span style="font-weight:800;font-size:18px;">Ravenzena Bot<\/span>/g, '<span style="font-weight:800;font-size:18px;"><%= siteSettings && siteSettings.siteName ? siteSettings.siteName : \'Ravenzena Bot\' %></span>'); 
html = html.replace(/view: \(null && "PENDING" === 'PENDING'\) \? 'checkout' : 'home',/, "view: (<%- JSON.stringify(typeof orderId !== 'undefined' ? orderId : '') %> && <%- JSON.stringify(typeof status !== 'undefined' ? status : 'PENDING') %> === 'PENDING') ? 'checkout' : 'home',"); 
html = html.replace(/pricing: \{.*?\},/s, "pricing: <%- JSON.stringify(typeof pricing !== 'undefined' ? pricing : {}) %>,"); 
html = html.replace(/contacts: \[.*?\],/s, "contacts: <%- JSON.stringify(typeof contacts !== 'undefined' ? contacts : []) %>,"); 
html = html.replace(/infoGroups: \{.*?\},/s, "infoGroups: <%- JSON.stringify(typeof infoGroups !== 'undefined' ? infoGroups : {}) %>,"); 
html = html.replace(/selectedBot: 'store',/, "selectedBot: '<%- typeof jenis_bot !== 'undefined' ? jenis_bot : 'store' %>',"); 
html = html.replace(/orderId: null,/, "orderId: <%- JSON.stringify(typeof orderId !== 'undefined' ? orderId : '') %>,"); 
html = html.replace(/qrisData: null,/, "qrisData: <%- JSON.stringify(typeof qris !== 'undefined' ? qris : '') %>,"); 
html = html.replace(/harga: 0,/, "harga: <%= typeof harga !== 'undefined' && harga ? harga : 0 %>,"); 
html = html.replace(/status: "PENDING",/, "status: <%- JSON.stringify(typeof status !== 'undefined' ? status : 'PENDING') %>,"); 
html = html.replace(/https:\/\/cdn\.jsdelivr\.net\/npm\/alpinejs@3\.x\.x\/dist\/cdn\.min\.js/g, 'https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js'); 
html = html.replace(/https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/font-awesome\/6\.5\.2\/css\/all\.min\.css/g, 'https://unpkg.com/@fortawesome/fontawesome-free@6.5.2/css/all.min.css'); 
fs.writeFileSync('views/index.ejs', html);
